### ISSUE TITLE
No TV responses after running commands

### ISSUE THREAD

**Issue by Jens-Wymeersch** [Palakis/esphome-native-hdmi-cec#11]
### The problem

After buying Black ESP-WROOM-32D, HDMI elbow pin and following the following post
https://www.facebook.com/groups/2431447663796200/permalink/3869957413278544/?rdid=yCqMcBiSAFqvF47L&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2Fp%2F1ATT9P3mn2%2F
I assume I was able to control my 'dumb' tv. None of the commands resulted in anything and I don't know why. Please note that the mqtt connection makes buttons in home assistant (hence the mqtt connection works perfectly)
I have connected cabling as follows 
V5 to V5
CEC GND to GND
CEC to GPIO26

### Which version of ESPHome was used when this happened?

2024.9.2

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
mqtt:
  broker: 'XX.YY.ZZ.UU'
  username: 'user'
  password: 'password'
  discovery: false # if you only want your own MQTT topics   

external_components:
  - source: github://Palakis/esphome-hdmi-cec

hdmi_cec:
  pin: GPIO26 # Required
  address: 0xE # Required
  physical_address: 0x4000 # Required
  osd_name: "Kitchen HDMI" # Optional. Defaults to "esphome"
  promiscuous_mode: false # Optional. Defaults to false
  monitor_mode: false # Optional. Defaults to false
  on_message:
    - opcode: 0x36 # opcode for "Standby"
      then:
        logger.log: "Got Standby command"
    
    # Respond to "Menu Request" (not required, example purposes only)
    - opcode: 0x8D
      then:
        hdmi_cec.send:
          # both "destination" and "data" are templatable
          destination: !lambda return source;
          data: [0x8E, 0x01] # 0x01 => "Menu Deactivated"
  
button:
  - platform: template
    name: "Turn all HDMI devices off"
    on_press:
      hdmi_cec.send:
        # "source" can optionally be set, like if you want to spoof another device's address
        destination: 0xF # Broadcast
        data: [0x36] # "Standby" opcode
  - platform: template
    name: TV Turn On
    on_press:
      - hdmi_cec.send:
          source: 0x05 # Optional since we'll default to `hdmi_cec.address`
          destination: 0x0
          data: [ 0x04 ] 
  - platform: template
    name: "Turn TV off"
    on_press:
      hdmi_cec.send:
        source: 1 #" can optionally be set, like if you want to spoof another device's address
        destination: 0 
        data: [0x36] 
  - platform: template
    name: "Volume up"
    on_press:
      hdmi_cec.send:
        #source:" can optionally be set, like if you want to spoof another device's address
        destination: 0x5 
        data: [0x44, 0x41] 
  - platform: template
    name: "Volume down"
    on_press:
      hdmi_cec.send:
        #source:" can optionally be set, like if you want to spoof another device's address
        destination: 0x5 
        data: [0x44, 0x42] 
  - platform: template
    name: "Mute"
    on_press:
      hdmi_cec.send:
        #source:" can optionally be set, like if you want to spoof another device's address
        destination: 0x5 
        data: [0x44, 0x43]
```
