### ISSUE TITLE
Templating 

### ISSUE THREAD

**Issue by Minims** [Palakis/esphome-native-hdmi-cec#2]
Hello, 

First of all thanks for this work !

I'm trying to get a Service in HomeAssistant. So i define this in esphome:

```
api:
  services:
    - service: hdmi_cec_send
      variables:
        cec_destination: int
        cec_data: int[]
      then:
        - hdmi_cec.send:
            destination: !lambda 'return cec_destination;'
            data: !lambda 'return cec_data;'
```

but i have this error : 

```
<unicode string>:54:14: error: could not convert 'cec_data' from 'vector<int>' to 'vector<unsigned char>'

```

Any Idea how i can fix this ?

**Comment by Minims** [comment]
fixed with that:
```
  services:
    - service: hdmi_cec_send
      variables:
        cec_destination: int
        cec_data: int[]
      then:
        - hdmi_cec.send:
            destination: !lambda 'return static_cast<unsigned char>(cec_destination);'
            data: !lambda 'std::vector<unsigned char> charVector; for (int i : cec_data) { charVector.push_back(static_cast<unsigned char>(i)); } return charVector;'
```
