### ISSUE TITLE
Unable to get the TV to turn on after power-cycling it

### ISSUE THREAD

**Issue by iDVB** [Palakis/esphome-native-hdmi-cec#3]
I have this simple code working and using HomeAssistant to send in...
```
cec_destination = 0
cec_data = [0x04]
```
...and its working to get the tv to turn on, but only when the tv is in standby mode. I'd really like to be able to turn the tv on from complete power-cycle as well. I only wired up 2 of the 3 (3rd was said to be optional) wires suggested in your readme. Perhaps 3 might work if the TV knows a device is there?

```yaml
services:
    - service: hdmi_cec_send
      variables:
        cec_destination: int
        cec_data: int[]
      then:
        - hdmi_cec.send:
            destination: !lambda 'return static_cast<unsigned char>(cec_destination);'
            data: !lambda 'std::vector<unsigned char> charVector; for (int i : cec_data) { charVector.push_back(static_cast<unsigned char>(i)); } return charVector;'
```

I can't believe I've been all over the place and can't seem to find a "programmatic solution to turn the tv on and off that is as guaranteed as the IR/RF remote. I was really hoping CEC would be the answer. 😢
