### ISSUE TITLE
Not working on Seeed Xiao ESP32-C3

### ISSUE THREAD

**Issue by segfly** [Palakis/esphome-native-hdmi-cec#7]
Very nice library, I'm glad someone refined the work from existing authors.

However, it's not working for me on `seeed_xiao_esp32c3`. It reports successfully transmitting frames in the logs, but on my logic analyzer I don't see the pin state change at all. I had the same issue with johnboiles library, and for the longest time, I thought the code just didn't work.

After discovering your library, and seeing that it still did not work for me, I decided to try it on a Waveshare ESP32-S3-Zero with `esp32-s3-devkitc-1` and it works fine.

So I am a bit perplexed what is going on, I've double and triple checked my physical connections, verified the pins work by testing other output components the same pin, tried all the pins available on the board, and still no output.

My config is very simple to test:
```yaml
esphome:
  name: basic

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
  # board: esp32-s3-devkitc-1 # Works for Waveshare ESP32-S3-Zero
  # framework:
  #   type: arduino

logger:

binary_sensor:
  - platform: gpio
    name: "CEC Send"
    pin:
      number: GPIO3    
      # number: GPIO0 # Waveshare ESP32-S3-Zero onboard button
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      hdmi_cec.send:
        destination: 0xF # Broadcast
        data: [0x36] # "Standby" opcode                

external_components:
  - source: github://Palakis/esphome-hdmi-cec

hdmi_cec:
  pin: GPIO4
  address: 0x4
  physical_address: 0x1000
```

Everything seems to be fine in the logs:
```
[D][binary_sensor:036]: 'CEC Send': Sending state ON
[D][hdmi_cec:204]: sending frame: 4F:36
[D][hdmi_cec:218]: HDMICEC::send(): frame sent and acknowledged
[W][component:237]: Component gpio.binary_sensor took a long time for an operation (53 ms).
[W][component:238]: Components should block for at most 30 ms.
[D][binary_sensor:036]: 'CEC Send': Sending state OFF
```

But only my S3 will actually output data, the C3 just sits there and pretends to have done something.

Thanks in advance for any pointers as to what may be going on.

**Comment by segfly** [comment]
After much debugging and testing, I compared the `HDMICEC::setup()` to other components that did work for output on the C3. The main difference I found was the lack of `pin_->setup()`. Once I added this to `HDMICEC::setup()` method.

I went back and tested this on my S3 as well, and it had no adverse effects. I don't have an RP2040 handy to test, but I doubt it would have an issue given all the other pin configuration by HDMICEC still occurs later for input/output mode.

As a side note, I went back and noticed that johnboiles library was also missing the `pin_->setup()`, which is probably why that library never worked for me on my C3 either.

**Comment by segfly** [comment]
Upon further testing (I missed a test case) the fix only resolves sending frames, not receiving frames.

**Comment by segfly** [comment]
I ended up finding a workaround to the `TG1WDT_SYS_RST` issue I was getting on the on the C3:

```yaml
esphome:
  name: basic
  platformio_options:
      board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
```

I ended up trying this combination because I noticed [the ESP32 task watchdog is not enabled when using the esp-idf framework](https://github.com/esphome/esphome/blob/83d3584173bd1eace81a967e0216017908b60392/esphome/components/esp32/core.cpp#L39-L43).

Along with the patch in PR #8, CEC receiving and sending frames now works as expected on the C3.

This is not ideal though, I actually wanted to use the Arduino framework for some library compatibility. I'm unsure why the TWDT is behaving so differently on the C3 than the S3. Perhaps moving the code in the ISR to the event loop would fix the issue. I might try that later, but it seems like that shouldn't be necessary.

Any pointers on a better fix for the `TG1WDT_SYS_RST` is appreciated.
